### ISSUE TITLE
Provide more information for failed workloads

### ISSUE THREAD

**Issue by rati3l** [perber/kdd#156]
Currently, if the workload is in failed state we display just this info:
![image](https://user-images.githubusercontent.com/34656130/236703743-703ed40f-bf74-49e9-933a-cb01b71cd873.png)
We can check the logs for pods in crashloop, etc, but in other cases (image pullbackoff, etc), we need to check the namespace events.

**Comment by perber** [comment]
Have you already checked the conditions field in the pod data. 
Maybe there is some information?
