### ISSUE TITLE
kdd crashes if the kube metrics server is not running in the cluster

### ISSUE THREAD

**Issue by rati3l** [perber/kdd#17]
Should we fail it more gracefully, leave it as is, or add some error handling (if the front end should be up and running even if the data is not collected)? 

`2023-01-05T19:29:17.968+0100    WARN    collector/workload_collector.go:301     could not load metrics data     {"error": "the server could not find the requested resource (get pods.metrics.k8s.io)"}
gitlab.com/patrick.erber/kdd/internal/collector.(*WorkloadCollector).collectContainerMetrics
        D:/go/kdd/internal/collector/workload_collector.go:301
gitlab.com/patrick.erber/kdd/internal/collector.(*WorkloadCollector).Collect
        D:/go/kdd/internal/collector/workload_collector.go:84
gitlab.com/patrick.erber/kdd/internal/controller.(*Controller).Run.func1
        D:/go/kdd/internal/controller/controller.go:45
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7ff6828808ee]

goroutine 28 [running]:
gitlab.com/patrick.erber/kdd/internal/collector.(*CollectorResult).GetNamespaceCollection(...)
        D:/go/kdd/internal/collector/workload_collector.go:57
gitlab.com/patrick.erber/kdd/internal/controller.(*Controller).Run.func1(0x0)
        D:/go/kdd/internal/controller/controller.go:46 +0xce
created by gitlab.com/patrick.erber/kdd/internal/controller.(*Controller).Run
        D:/go/kdd/internal/controller/controller.go:42 +0x12e
exit status 2`

**Comment by perber** [comment]
I would say that the error should be printed out and a log message should be displayed. In the UI we should just say that the application is not able to scrape metrics. 
I guess the best will be if the ui is still running as expected.

**Comment by perber** [comment]
Or do you have other suggestions?
