### ISSUE TITLE
Define how we can gather feedback and exchange with others

### ISSUE THREAD

**Issue by perber** [perber/kdd#26]
We need to find a way to exchange ideas & have a room for fast discussions. 

2 possibilites came to my mind. 

* Discord
* Github Discussions

**Comment by rati3l** [comment]
I'd say GitHub Discussions for more external, and async stuff, and discord for day-to-day fast discussions.
Slack would be also fine, but the free version keeps the chat history only for 90 days. 
I've sent you an invite to a discord channel, we can try it out and see how it works for us.

**Comment by perber** [comment]
Thx, for creating the discord channel. I think this is a good solution to start with and do make the communication much easier.

**Comment by perber** [comment]
If we need more we will create a new ticket to work on the communication again.
