### ISSUE TITLE
Setting up Docker CI/CD Pipeline

### ISSUE THREAD

**Issue by perber** [perber/kdd#3]
To ensure rapid and error-free development, the creation of a CI/CD pipeline is planned. 

In addition to quality gates, this pipeline will also carry out automated tests.

**Acceptance Criteria**
- Create a simple pipeline for building the Docker image.
- Create more tickets to improve the CI/CD process and testing.

**Comment by rati3l** [comment]
GitHub actions should be acceptable for this, we have [2000 minutes of server time](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions) per month. 

One build takes around 3 minutes on my machine.

steps in the pipeline:
fetch the repo
run go test ./...
run docker login
run docker build
push the docker image

For now the docker secrets can be [encrypted in the repo](https://docs.github.com/en/actions/security-guides/encrypted-secrets).
