### ISSUE TITLE
evaluate chart library we want to use to display metrics

### ISSUE THREAD

**Issue by perber** [perber/kdd#30]
In our dashboard also charts should be displayed. 
Therefore we need to gather information what type of graphs we need and find the best matching library for our usecases. 

**Acceptance Criteria**
* Documentation about the evaluation process
* Decision made for chart library

**Comment by rati3l** [comment]
Chart.js is the most used library for that and comes with batteries included - a close second is d3.js, but judging from docs it seems like we'd need to build the graphs ourselves when in charts.js we'd use ready-made components.

Ex. sample code for line graph from docs:
https://www.chartjs.org/docs/latest/samples/scales/linear-min-max.html

**Comment by perber** [comment]
This is the react version of chartjs: https://react-chartjs-2.js.org/

**Comment by perber** [comment]
We have decided to use chartjs for that. 
chartjs is already used to display mem & cpu usage
